version: "3.7"
services:
  firebase:
    build: .
    volumes:
      - ./functions:/app/functions
      - ./firebase.json:/app/firebase.json
      - ./.firebaserc:/app/.firebaserc
    ports:
      - "4000:4000"
      - "5001:5001"
      - "8080:8080"
      - "9099:9099"
    working_dir: /app
    command: ["firebase", "emulators:start", "--project", "local-project"]
